name: 刷步数

on:
  schedule:
    - cron: '47 1,4,7,12,14,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
          
      - name: 开始
        env:
            CONFIG: {
    "USER": "908090958@qq.com#861039935@qq.com",
    "PWD": "hg8521456#HhHh1234.",
    "MIN_STEP": "25000",
    "MAX_STEP": "40000",
    "PUSH_PLUS_TOKEN": "",
    "PUSH_PLUS_HOUR": ""
  }
        run: |
          pip3 install requests pytz
          python3 main.py
